# Applicant Tracking System: Resume and Job Description Matches

*Replace this text with your summary, including research questions as a numbered list and answers for each research questions.*

This is an applicant tracking system, often refered to as an ATS. They are commonly used by companies and businesses of all sizes, and they serve to sort through applicant resumes and return a subset as the best possible canidates for the job. Such 

1. What factors distinguish a good match versus a bad one between a job and a resume?\
**ANS:** 
2. Does direct word matching between a resume and description indicate a better match, or do synonyms perform just as well?\
**ANS:** 
3. How does an ATS handle applicant demographics? How are inclusion and bias handled?\
**ANS:**

## Challenge Goals

*Replace this text with your challenge goals. If the challenge goals were scaled back or expanded, explain why the task turned out differently than initially estimated.*

- **New library:** Natural Language Processing: Resumes and job descriptions, by nature of their use, must be human focused and readable. But with the precedent set by companies like linkedin, indeed, and glassdoor, matches between job descriptions and resumes are needed on a much faster and larger scale, and natural language processing is especially helpful for this. Parsing out the meaning and synonyms of words is especially important for 
- **Multiple data sets:**  Resumes and job descriptions have a lot of room for variety, and multiple data sets can provide different types of resumes and job descriptions.

## Collaboration and Conduct

Students are expected to follow Washington state law on the [Student Conduct Code for the University of Washington](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html). In this course, students must:

- Indicate on your submission any assistance received, including materials distributed in this course.
- Not receive, generate, or otherwise acquire any substantial portion or walkthrough to an assessment.
- Not aid, assist, attempt, or tolerate prohibited academic conduct in others.

Update the following code cell to include your name and list your sources. If you used any kind of computer technology to help prepare your assessment submission, include the queries and/or prompts. Submitted work that is not consistent with sources may be subject to the student conduct process.

In [ ]:
your_name = "Ilse Schmitz"
sources = [
    ...
]

assert your_name != "", "your_name cannot be empty"
assert ... not in sources, "sources should not include the placeholder ellipsis"
assert len(sources) >= 6, "must include at least 6 sources, inclusive of lectures and sections"

## Data Setting and Methods

*Replace this text with a description of the data setting, any data transformations you conducted, and the methods you plan to use to answer the research questions. You may remove the code cell below if you don't need it.*

In [1]:
import pandas as pd

In [19]:
job_desc = pd.read_csv('job-desc-dataset\\jts.csv')
job_desc

,id,Job Title,Job Description
0,0,Flutter Developer,We are looking for hire experts flutter develo...
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2,2,Machine Learning,"Data Scientist (Contractor)\n\nBangalore, IN\n..."
3,3,iOS Developer,JOB DESCRIPTION:\n\nStrong framework outside o...
4,4,Full Stack Developer,job responsibility full stack engineer – react...
...,...,...,...
2272,2399,Backend Developer,Job Summary\nPublished on : 26 days ago\nVacan...
2273,2400,Full Stack Developer,business entity cisco umbrella focus cloud-bas...
2274,2401,Network Administrator,Urgently reqd in a college in Mohali\nNetwork ...
2275,2402,Machine Learning,Key Responsibilities: Team leads for small or ...
2276,2403,Full Stack Developer,leslie hindman auctioneer one nation 's leadin...

In [21]:
resume_valid = pd.read_csv('resume-data\\validation.csv')
resume_valid
resume_train = pd.read_csv('resume-data\\train.csv')
resume_train
resume_test = pd.read_csv('resume-data\\test.csv')
resume_test

                                            Resume_str              Category
0    SOCIAL MEDIA COMMUNICATIONS MANAGER Education ...      PUBLIC-RELATIONS
1    TEACHER Willing relocate: Anywhere Professiona...               TEACHER
2    PRINCIPAL CONSULTANT Executive Profile A dynam...               BANKING
3    SENIOR ASSOCIATE Executive Profile Seasoned Fi...               BANKING
4    ACCOUNTANT Professional Summary I enthusiastic...            ACCOUNTANT
..                                                 ...                   ...
493  ENGINEERING OFFICER Objective Looking opportun...           ENGINEERING
494  BUSINESS DEVELOPMENT MANAGER Summary Understan...  BUSINESS-DEVELOPMENT
495  HEAD GIRLS BASKETBALL COACH Summary Former col...               FITNESS
496  PRESIDENT Executive Profile Media relations pr...      PUBLIC-RELATIONS
497  FINANCE DIRECTOR Executive Profile Dedicated a...               FINANCE

[498 rows x 2 columns]

In [25]:
resume_job_match = pd.read_csv('resume-job-match\\resume_data.csv')
resume_job_match

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9539,NaN,NaN,"['Mathematical modelling', 'Machine Learning',...",['Sanghvi College of Engineering'],['B.Tech'],['2019'],['N/A'],['N/A'],['N/A'],['BPM Foundation'],...,NaN,NaN,NaN,Data Engineer,Bachelor of Science (BSc),5 to 8 years,NaN,Data Platform Design\nData Pipeline Developmen...,Azure\nBig Data\nData Analytics\nETL Tools\nPo...,0.683333
9540,NaN,Expertise EDA modeler. I like to learn what my...,"['Data Analysis', 'Business Analysis', 'Machin...","['KVoCT, Pune', 'KVoCT, Pune']","['B.CA', 'M.CA']","['2018', '2020']","[None, None]","[None, None]","[None, None]",['Passionate Solution'],...,NaN,NaN,NaN,Executive/ Sr. Executive -IT,Bachelor of Science (BSc) in Computer Science ...,3 to 5 years,Age at most 40 years,Hardware & Software Installation\nSystem Monit...,NaN,0.650000
9541,NaN,Looking for roles related to application devel...,"['Business Analyst', 'Data Analytics', 'Data C...",['PGG College Mysore'],['B.BA'],['2019'],['N/A'],['N/A'],['N/A'],['ZigSAW'],...,NaN,NaN,NaN,Executive - VAT,BBA in Accounting and Finance,1 to 3 years,NaN,Mushak Forms Maintenance\nVAT Software & MS Of...,VAT and Tax,0.650000
9542,NaN,NaN,"['Machine Learning', 'Natural Language Process...","['Rajiv Gandhi Memorial University, Delhi']",['B.TECH'],['2020'],['N/A'],['N/A'],['Electrical'],['Zynta Labs'],...,[None],[None],[None],Asst. Manager/ Manger (Administrative),Bachelor/Honors,At least 5 years,Age at least 28 years,Administrative Support\nScheduling\nFiling & D...,•Administration\n•Health Safety and Environmen...,0.650000
9543,NaN,NaN,"['assisted living', 'interpersonal and communi...",['ARIZONA STATE UNIVERSITY'],['B.A'],['N/A'],['Cum Laude'],['N/A'],['Organizational Communication Business Manage...,"['Company Name', 'Company Name', 'Company Name...",...,NaN,NaN,NaN,Civil Engineer,B.Sc in Civil Engineering from a reputed unive...,At least 5 years,Age at least 30 years,Design Review\nCoordination\nProposal Preparat...,AutoCAD\nETABS\nMicrosoft Office Suite\nMS Pro...,0.650000

In [29]:
merged_data = pd.read_csv('resume-job-company\\merged_dataset.csv')
hris_master_fake = pd.read_csv('resume-job-company\\hris_master_table_fake.csv')
comp_pos_master_fake = pd.read_csv('resume-job-company\\company_position_master_table_fake.csv')
linkedin = pd.read_csv('resume-job-company\\Company_LinkedIN_MasterTable.csv')
ats = pd.read_csv('resume-job-company\\ats_master_table_fake.csv')

C:\Users\User\AppData\Local\Temp\ipykernel_3848\73438662.py:1: DtypeWarning: Columns (1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_data = pd.read_csv('resume-job-company\\merged_dataset.csv')
C:\Users\User\AppData\Local\Temp\ipykernel_3848\73438662.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  hris_master_fake = pd.read_csv('resume-job-company\\hris_master_table_fake.csv')
C:\Users\User\AppData\Local\Temp\ipykernel_3848\73438662.py:3: DtypeWarning: Columns (3,7,9) have mixed types. Specify dtype option on import or set low_memory=False.
  comp_pos_master_fake = pd.read_csv('resume-job-company\\company_position_master_table_fake.csv')
C:\Users\User\AppData\Local\Temp\ipykernel_3848\73438662.py:5: DtypeWarning: Columns (2,7,13) have mixed types. Specify dtype option on import or set low_memory=False.
  ats = pd.read_csv('resume-job-company\\ats_master_table_fake.csv')

In [31]:
merged_data

,Unnamed: 0,Hired_Status,Employee_ID,Applied_Job_ID,Job_loc_state,YOB,Start_Time,Change_Reason,Job_Role_ID,Job_Role_Name_Internal,...,company_name,company_industry,company_url,company_location_country,company_location_region,company_size,position_level,position_location,position_title,position_start_date
0,1737,True,FR004,920625,VA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1797,True,MIH200,1596394,VA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1805,True,STEVRO01,1637566,VA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1809,True,ZIMMRA01,1658104,VA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1867,True,WATKZA01,1673894,VA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906120,463778,NaN,58150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,amn healthcare,staffing and recruiting,linkedin.com/in/victoriariingen,united states,texas,1001-5000,['senior'],[],senior recruiter,2020-12
906121,463779,NaN,DALLJE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"p1 group, inc.",construction,linkedin.com/in/jeff-dallas-0a273949,united states,kansas,1001-5000,['manager'],"['lenexa, kansas, united states']",project manager,2009-04
906122,463780,NaN,MADDMA01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"p1 group, inc.",construction,linkedin.com/in/matt-maddox-93a82771,united states,kansas,1001-5000,[],[],field coordinator,2011
906123,463781,NaN,PATTCH01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,the waldinger corporation,construction,linkedin.com/in/christopher-patterson-36964a101,united states,iowa,1001-5000,['training'],"['wichita, kansas, united states']",project engineer and intern,2014-05
906124,463782,NaN,PATTCH01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"p1 group, inc.",construction,linkedin.com/in/christopher-patterson-36964a101,united states,kansas,1001-5000,[],"['lenexa, kansas, united states']",project engineer,2015-05-01

## Building Process -- RESTRUCURE

This is not part of the project. This is where I am building my ATS

In [13]:
!pip install spacy

Requirement already satisfied: spacy in c:\users\user\downloads\python3\lib\site-packages (3.8.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (4.66.4)
Requirement already satisfied: numpy>=1.19.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (2.32.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: jinja2 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\user\downloads\python3\lib\site-packages (from spacy) (69.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\user\downloads\python3\lib\site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in c:\users\user\downloads\python3\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\user\downloads\python3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\users\user\downloads\python3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.14.6)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\user\downloads\python3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\downloads\python3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\downloads\python3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\downloads\python3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\downloads\python3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.8.30)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in c:\users\user\downloads\python3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.2.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\user\downloads\python3\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\user\downloads\python3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\user\downloads\python3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\user\downloads\python3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\user\downloads\python3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.3.5)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\user\downloads\python3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\user\downloads\python3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\downloads\python3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\user\downloads\python3\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\user\downloads\python3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\user\downloads\python3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\user\downloads\python3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)

In [14]:
import spacy

TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

In [ ]:
text = "The rain in Spain falls mainly on the plain."
doc = nlp(text)

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.is_stop)

## Results

*Replace this text with your results. This section tends to be one of the longer sections of the notebook. Be sure to create new code cells and new Markdown text cells with additional subheadings to explain and break-up longer snippets of code into a more readable format.*

1. *Present and discuss your research results. Treat each of your research questions separately. Include additional discussions for results that are most interesting, surprising, or important.*
2. *Interpret the results. If the answers are unexpected, try to offer an explanation. A good report not only presents the results, but also provides an argument or interpretation based on the data analysis.*
3. *Include any visualizations you have made. In general, these should be generated by your Python code. If you plotted by hand or other software, explain why it was not possible to create the plot you wanted in Python and what you tried.*

*As with assessments, documentation and testing are required. Automated tests must be written in Python using small, manually-verifiable data.*

## Implications and Limitations

*Replace this text with your analysis. Who might benefit from your analysis and who might be excluded or otherwise harmed by it? What about the data setting might have impacted your results? Explain at least 3 limitations of your analysis and how others should or shouldn't be advised to use your conclusions. You may remove the code cell below if you don't need it.*